# Generated by Django 3.0.14 on 2024-11-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceprod',
            old_name='dateverity',
            new_name='dateverify',
        ),
    ]
